test: cicd workflow
Signed-off-by: Ilona Shishov <Ilona.Shishov@gmail.com>

diff --git a/.github/workflows/cicd.yaml b/.github/workflows/cicd.yaml
--- a/.github/workflows/cicd.yaml
+++ b/.github/workflows/cicd.yaml
@@ -32,6 +32,8 @@ jobs:
   validate_workflow_requirements:
     runs-on: ubuntu-latest
 
+    if: github.repository == 'IlonaShishov/exhort'
+
     steps:
       - name: Check For Required Secrets
         uses: actions/github-script@v6
@@ -71,9 +73,7 @@ jobs:
   build_and_push_image:
     needs: validate_workflow_requirements
     runs-on: ubuntu-latest
-    
-    if: github.repository == 'IlonaShishov/exhort'
-    
+        
     outputs:
       digest: ${{ steps.push-to-quay.outputs.digest }}
 
@@ -134,4 +134,15 @@ jobs:
           oc patch deployment ${{ env.OPENSHIFT_DEPLOYMENT_NAME }} -p "${DEPLOYMENT_PATCH}"
 
       - name: Monitor Deployment Status
-        run: oc rollout status deployment/${{ env.OPENSHIFT_DEPLOYMENT_NAME }}
+        run: |
+          set +e # Disable exit on error temporarily
+          error_message=$(oc rollout status deployment/${{ env.OPENSHIFT_DEPLOYMENT_NAME }} 2>&1)  # Capture error message
+          STATUS=$?
+          if [ $STATUS -ne 0 ]; then
+            echo "Error: Deployment failed."
+            echo "$error_message"  # Echo the error message
+            exit 1
+          fi
+          echo "Deployment completed successfully."
+          echo "$error_message"  # Echo the error message
+          set -e # Enable exit on error again
